stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build-job:
  stage: build
  tags:
    - local
  script:
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - "*/target/*.jar"
    expire_in: 1 hour

test-job:
  stage: test
  tags:
    - local
  script:
    - mvn test "-Dspring.profiles.active=ci"
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  only:
    - main
  tags:
    - local
  script:
    - echo "Building JAR files first..."
    - mvn clean package -DskipTests
    - echo "Logging in to Docker Hub..."
    - docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_TOKEN
    - echo "Building auth-service image..."
    - docker build -t "$($env:DOCKERHUB_USERNAME)/auth-service:latest" ./auth-service
    - echo "Building user-service image..."
    - docker build -t "$($env:DOCKERHUB_USERNAME)/user-service:latest" ./user-service
    - echo "Pushing images to Docker Hub..."
    - docker push "$($env:DOCKERHUB_USERNAME)/auth-service:latest"
    - docker push "$($env:DOCKERHUB_USERNAME)/user-service:latest"
    - echo "Deploy successful!"
  dependencies:
    - build-job