<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Kế thừa từ Spring Boot để tự động quản lý version các dependency -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.4</version>
        <relativePath/>
    </parent>

    <groupId>com.r2s</groupId>
    <artifactId>user-access-management</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <!-- packaging = pom nghĩa là đây là project cha, không build thành JAR -->
    <packaging>pom</packaging>

    <!-- Khai báo các module con, Maven sẽ build theo thứ tự này -->
    <modules>
        <module>core</module>
        <module>auth-service</module>
        <module>user-service</module>
    </modules>

    <properties>
        <java.version>17</java.version>
    </properties>

    <!-- dependencyManagement: định nghĩa version tập trung -->
    <!-- Các module con dùng dependency này sẽ không cần ghi version nữa -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.r2s</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.7.3</version>
            </dependency>

            <!-- Thêm JWT versions vào đây -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>0.11.5</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>0.11.5</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>0.11.5</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>